---
langage: python
python:
  - 3.9
addons:
  rethinkdb: 2.3

env:
  RM_HOST: localhost

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - sudo service rethinkdb start && sleep 5
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
