---
langage: python
python:
  - 3.9
addons:
  rethinkdb: "2.3"

env:
  - RM_HOST="localhost"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - sudo service rethinkdb restart && sleep 10
  - make test

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage-reports/coverage.xml
